### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by rabaimorp** [Moderpach/Extinguish_package#11]
Why is this on github if its closed source? I really want to use this, but beeing closed source for seemingly no reason worries me. Are there any plans to open source this in the future? (or at least source available)

**Comment by Moderpach** [comment]
Yes, I plan to open source the next version. Version control is a mess right now. I need to organize the project.

**Comment by rabaimorp** [comment]
Thats amazing! Can't wait (;

**Comment by rabaimorp** [comment]
> Yes, I plan to open source the next version. Version control is a mess right now. I need to organize the project.

Is the project dead, or is it still in consideration after 7 months?

**Comment by Moderpach** [comment]
> > Yes, I plan to open source the next version. Version control is a mess right now. I need to organize the project.
> 
> Is the project dead, or is it still in consideration after 7 months?

It's alive.

**Comment by rabaimorp** [comment]
You did it 🎉
