### ISSUE TITLE
One UI 6 update issue? 

### ISSUE THREAD

**Issue by Phoenixsouls** [Moderpach/Extinguish_package#2]
I was using the app for quite some time now but I updated my S23 Ultra to One UI 6... I got this error instead..

java.lang.ReflectiveOperationException: java.lang.NoSuchMethodException: android.view.SurfaceControl.getInternalDisplayToken []

My phone is on android 14.

I have this running on shizuku non root wifi debug only.

 Any ideas on how to get this back to work again?

**Comment by Moderpach** [comment]
Extinguish is not support Android 14 now because Android 14 removes the function to set display state by apps. I am trying to reimplante it with black window or extra dark but It won't be as effective and handy as previous methods.
