### ISSUE TITLE
Not working on samsung galaxy m13 with android 14

### ISSUE THREAD

**Issue by Ktosnapewno999** [Moderpach/Extinguish_package#5]
IT gives error java.lang.ReflectiveOperationException: java.lang.NoSuchMethodException: android.view.SurfaceControl.getInternalDisplayToken []

**Comment by Moderpach** [comment]
Android 14 is now unsupported. Old implementation has been broken. I would try to reimplantation it to support android 14 in next build.

**Comment by PakinDeReal** [comment]
any update on android 14?

**Comment by Ktosnapewno999** [comment]
No
